version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@2.1.0
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run :
          name : Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy: 
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project

workflows:
  test_foodive:
    jobs:
      - cypress/run:
          start: npm start
      - build
      - deploy:
          requires:
            - cypress/run
            - build
          filters:
            branches:
              only: main
 