version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@2.1.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run cy:run
      - run :
          name : Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy: 
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           start: npm start

workflows:
  test_my_app:
    jobs:
      - cypress/run:
          start: npm start
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
 