const options = [
    "American",
    "Mexican",
    "Italian",
    "Fast Food",
    "Thai",
    "Japanese",
    "Vietnamese",
    "Chinese",
    "Mediterranean",
    "Deli",
    "Korean",
    "French",
    "Pizza",
    "Breakfast",
    "Diner",
    "Seafood",
    "Donuts",
    "Sushi",
    "Greek",
    "Cajun",
    "Barbeque",
    "Indian",
    "Vegetarian",
    "Burgers",
    "Fine Dining",
    "Soul Food",
    "Steaks",
    "Tapas",
    "Bakery",
    "Caribbean",
    "Wings"
]

export default options