const options = [
    {displayName: "American", requestName: "newamerican"},
    {displayName: "Mexican", requestName: "mexican"},
    {displayName: "Italian", requestName: "italian"},
    {displayName: "Fast Food", requestName: "hotdogs"},
    {displayName: "Thai", requestName: "thai"},
    {displayName: "Japanese", requestName: "japanese"},
    {displayName: "Vietnamese", requestName: "vietnamese"},
    {displayName: "Chinese", requestName: "chinese"},
    {displayName: "Mediterranean", requestName: "mediterranean"},
    {displayName: "Deli", requestName: "delis"},
    {displayName: "Korean", requestName: "korean"},
    {displayName: "French", requestName: "french"},
    {displayName: "Pizza", requestName: "pizza"},
    {displayName: "Breakfast", requestName: "breakfast_brunch"},
    {displayName: "Diner", requestName: "diners"},
    {displayName: "Seafood", requestName: "seafood"},
    {displayName: "Donuts", requestName: "donuts"},
    {displayName: "Sushi", requestName: "sushi"},
    {displayName: "Greek", requestName: "greek"},
    {displayName: "Cajun", requestName: "cajun"},
    {displayName: "Barbeque", requestName: "barbeque"},
    {displayName: "Indian", requestName: "indpak"},
    {displayName: "Vegetarian", requestName: "vegetarian"},
    {displayName: "Burgers", requestName: "burgers"},
    {displayName: "Soul Food", requestName: "soulfood"},
    {displayName: "Steakhouses", requestName: "steak"},
    {displayName: "Tapas", requestName: "tapasmallplates"},
    {displayName: "Bakery", requestName: "bakeries"},
    {displayName: "Caribbean", requestName: "caribbean"},
    {displayName: "Wings", requestName: "chicken_wings"}
]

export default options